### ISSUE TITLE
Duplicate ModuleResourceActions2

### ISSUE THREAD

**Issue by Wercho** [SirDiazo/ModActions#1]
Because some MFT patches (and probably Fuel Switch patches) don't remove the RESOURCE nodes from the config, I suggest changing the part.cfg file to avoid adding duplicate ModuleResourceActions2 modules to those parts.

Suggested change:

```
@PART[*]:HAS[@MODULE[TankContentSwitcher]&!MODULE[ModuleResourceActions2]]:Final
{
MODULE
{
name = ModuleResourceActions2
}
}

@PART[*]:HAS[@MODULE[ModuleFuelTanks]&!MODULE[ModuleResourceActions2]]:Final
{
MODULE
{
name = ModuleResourceActions2
}
}

@PART[*]:HAS[@RESOURCE[*]&!MODULE[ModuleResourceActions2]]:Final
{
MODULE
{
name = ModuleResourceActions2
}
}
```

**Comment by SirDiazo** [comment]
Oh, I didn't realize that could happen.

I'll add this to the next update.

**Comment by SirDiazo** [comment]
And added to release 1.1
